--- # Delete Azure VM from RHAAP survey input

- name: Delete Azure VM
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    resource_group_name: "exl"   # hardcode or add to survey if dynamic

  tasks:
    - name: Delete the Virtual Machine (keep other resources)
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        state: absent
      register: delete_result

    - name: Show deletion result
      debug:
        var: delete_result
